language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

before_install:
  - composer self-update

install:
  - composer update

script:
  - phpunit --coverage-text

notifications:
  email:
    - pdfbundle@siphoc.com
